Add choc v1 & v2 led cutout marks support
ceoloide/ergogen-footprints pull request #28
Opened 2024-05-06 02:04 UTC by mlilley

Useful for positioning components (ie: leds) within the cutout. 

Dimensions taken from Kailh specs:
v1: http://www.kailh.com/en/Products/Ks/CS/319.html
v2: http://www.kailh.com/en/Products/Ks/CS/755.html

![output](https://github.com/ceoloide/ergogen-footprints/assets/20426/4ac738d1-1230-4c7f-bf25-0c9f63e1b178)

2024-05-06 13:06 UTC, ceoloide commented on switch_choc_v1_v2.js
Do you mind converting the 4 lines to a single rectangle? Thanks!

2024-05-06 19:53 UTC, mlilley commented on switch_choc_v1_v2.js
Done

2024-05-06 21:18 UTC, ceoloide requested changes

2024-05-06 21:18 UTC, ceoloide commented on switch_choc_v1_v2.js
> +    (fp_line (start -2.65 6.325) (end 2.65 3.075) (layer "Dwgs.User") (width 0.15) (stroke (width 0.15) (type solid)))
Should be `fp_rect`

2024-05-06 21:18 UTC, ceoloide commented on switch_choc_v1_v2.js
> +    (fp_line (start -2.75 6.405) (end 2.75 3.455) (layer "Dwgs.User") (width 0.15) (stroke (width 0.15) (type solid)))
Should be `fp_rect`

2024-05-06 21:37 UTC, mlilley commented on switch_choc_v1_v2.js
> +    (fp_line (start -2.65 6.325) (end 2.65 3.075) (layer "Dwgs.User") (width 0.15) (stroke (width 0.15) (type solid)))
Eugh :( fixed.

2024-05-07 01:35 UTC, ceoloide approved these changes

2024-05-07 01:35 UTC, merged

2024-05-07 01:35 UTC, ceoloide commented
Thanks for your contribution!